// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeDL;

#nullable disable

namespace PokeDL.Migrations
{
    [DbContext(typeof(PokeDbContext))]
    [Migration("20220310173220_AddedM2M")]
    partial class AddedM2M
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AbilityPokemon", b =>
                {
                    b.Property<int>("AbilitiesAbId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonsPokeId")
                        .HasColumnType("int");

                    b.HasKey("AbilitiesAbId", "PokemonsPokeId");

                    b.HasIndex("PokemonsPokeId");

                    b.ToTable("AbilityPokemon");
                });

            modelBuilder.Entity("PokeModel.Ability", b =>
                {
                    b.Property<int>("AbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbId"), 1L, 1);

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PP")
                        .HasColumnType("int");

                    b.Property<int>("PokemonPokeId")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.HasKey("AbId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("PokeModel.Pokemon", b =>
                {
                    b.Property<int>("PokeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PokeId"), 1L, 1);

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("PokeId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("AbilityPokemon", b =>
                {
                    b.HasOne("PokeModel.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesAbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeModel.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("PokemonsPokeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
